{% set name = "command_line_tools" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - git_url: https://github.com/neuromorphic-paris/command_line_tools.git
  - path: CMakeLists.txt

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - git
  host:
    - pthread-stubs

test:
  commands:
    - test -f $PREFIX/bin/event_rate

about:
  home: https://github.com/neuromorphic-paris/command_line_tools
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Command-line tools bundles command-line applications to manipulate event files.

extra:
  recipe-maintainers:
    - Tobias-Fischer
